const SET_BOOKS = "SET_BOOKS";
const GET_BOOKS = "GET_BOOKS";
const ADD_BOOK = "ADD_BOOK";
const UPDATE_BOOK = "UPDATE_BOOK";
const LOAD_BOOKS = "LOAD_BOOKS";
const SET_FILTER = "SET_FILTER";
const SEARCH_BOOKS = "SEARCH_BOOKS";
const SEARCH_BY = "SEARCH_BY";
const SORT_BOOKS = "SORT_BOOKS"
const SELECT_DIRECTION = "SELECT_DIRECTION"

export {
    SET_BOOKS,
    GET_BOOKS,
    ADD_BOOK,
    LOAD_BOOKS,
    SET_FILTER,
    SEARCH_BOOKS,
    SORT_BOOKS,
    UPDATE_BOOK,
    SEARCH_BY,
    SELECT_DIRECTION
}